# Generated by Django 5.0.7 on 2024-08-02 05:50

import football_fields.validates_function
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='field_images/', validators=[football_fields.validates_function.validate_image_size])),
            ],
            options={
                'verbose_name': 'Field Image',
                'verbose_name_plural': 'Field Images',
                'db_table': 'field_images',
            },
        ),
        migrations.CreateModel(
            name='FootballField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name not identified', max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=13)),
                ('price_per_hour', models.FloatField(validators=[football_fields.validates_function.price_per_hour_validator])),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Football Field',
                'verbose_name_plural': 'Football Fields',
                'db_table': 'football_fields',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'reservations',
            },
        ),
    ]
