# Generated by Django 5.0.7 on 2024-08-02 05:50

import django.db.models.deletion
import football_fields.validates_function
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('football_fields', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='footballfield',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to=settings.AUTH_USER_MODEL, validators=[football_fields.validates_function.validate_owner]),
        ),
        migrations.AddField(
            model_name='fieldimage',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='football_fields.footballfield'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='field',
            field=models.ManyToManyField(related_name='reservations', to='football_fields.footballfield'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='footballfield',
            index=models.Index(fields=['name'], name='football_fi_name_984c62_idx'),
        ),
        migrations.AddIndex(
            model_name='footballfield',
            index=models.Index(fields=['address'], name='football_fi_address_3cf23e_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['start_time'], name='reservation_start_t_f02bee_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['end_time'], name='reservation_end_tim_347470_idx'),
        ),
    ]
