# Generated by Django 5.0.7 on 2024-08-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_fields', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballfield',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footballfield',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
